modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="balizalandmod"
version="1.0.0"
displayName="Baliza Land Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Yo, MCreator"

[[dependencies.balizalandmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




